### ISSUE TITLE
AppMap extension generates findings in JetBrains extension

### ISSUE THREAD

**Issue by ahtrotta** [getappmap/appmap-intellij-plugin#92]
Currently, scans are failing. The following error message is shown in our `#telemetry` slack:

![Image](https://user-images.githubusercontent.com/45714532/186766555-fac63dbc-de35-4320-9be0-891d245b7214.png)

You might need to use the `--all` flag when running the scan

**Comment by jansorg** [comment]
Adding --all on the command line still terminates early:
```
$ /home/jansorg/Downloads/scanner-linux-x64 scan --watch --all
Don't use --all with --watch, because in watch mode all findings are reported
```

I tried to replicate the commandline used by VSCode. Is this different to the CLI binaries, perhaps?
https://github.com/applandinc/vscode-appland/blob/dd300d62ed06e5f929d765f76af54d91922f4820/src/services/nodeProcessService.ts#L57-L78

**Comment by petecheslock** [comment]
At least while running on the command line passing an `--all` will avoid the API key check, but looking at the code you linked i'm not sure where in the vscode flow do we bypass the API key check.

**Comment by jansorg** [comment]
This should be fixed by the latest releases of the CLI binaries.

**Comment by dividedmind** [comment]
I'm still not getting any findings. The plugin on its own seems to run `scan --watch` alright, but the results go to nil. When I run `scan` manually, `appmap-findings.json` file is created but the findings still don't show up in IntelliJ.

**Comment by ahtrotta** [comment]
I'm still not getting findings. Even if I run `npx @appland/scanner scan --watch` manually, nothing happens. If I run `npx @appland/scanner scan --all` then I get findings.

**Comment by jansorg** [comment]
Could you test this again with the latest 0.8.1-7 preview at https://github.com/applandinc/appmap-intellij-plugin/releases/tag/install-guide-preview? I believe it's fixed now

**Comment by jansorg** [comment]
I was able to reproduce the problem of the "unknown file" items. Will be fixed by the next update.

**Comment by jansorg** [comment]
Closing this, because findings are now supported and the reported issues should be fixed already.
cc @ahtrotta
